### ISSUE TITLE
Problems running Angular2_Dev

### ISSUE THREAD

**Issue by FacundoGFlores** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#17]
After doing: `npm install`
I get the following:
```
Projects\CoreUI-Free-Bootstrap-Admin-Template\Angular2_Dev>npm start

> CoreUI@1.0.0-alpha.1 start ..\Projects\CoreUI-Free-Bootstrap-Admin-Template\Angular2_Dev
> tsc && concurrently "tsc -w" "lite-server"

app/widgets/widgets.component.ts(360,9): error TS1005: ',' expected.
```

I changed the file `widgets.component.ts` file:
```
elements: { point: { radius: 0 } },
        legend: {
            display: false
        }
};
```

Now, I did `npm start again` and I get:

```
> CoreUI@1.0.0-alpha.1 start \Projects\CoreUI-Free-Bootstrap-Admin-Template\Angular2_Dev
> tsc && concurrently "tsc -w" "lite-server"

app/layouts/full-layout.component.ts(3,10): error TS2305: Module '"/Projects/CoreUI-Free-Bootstrap-Admin-Template/Angular2_Dev/node_modules/ng2-bootstrap/ng2-bootstrap"' has no exported member 'DROPDOWN_DIRECTIVES'.
app/layouts/full-layout.component.ts(4,10): error TS2305: Module '"/Projects/CoreUI-Free-Bootstrap-Admin-Template/Angular2_Dev/node_modules/ng2-bootstrap/ng2-bootstrap"' has no exported member 'TAB_DIRECTIVES'.
node_modules/ng2-bootstrap/components/utils/components-helper.service.d.ts(45,45): error TS2315: Type 'Type' is not generic.
node_modules/ng2-bootstrap/components/utils/components-helper.service.d.ts(56,41): error TS2315: Type 'Type' is not generic.
app/app.module.ts(5,10): error TS2305: Module '"/Projects/CoreUI-Free-Bootstrap-Admin-Template/Angular2_Dev/node_modules/ng2-bootstrap/ng2-bootstrap"' has no exported member 'DROPDOWN_DIRECTIVES'.
```

**Comment by mrholek** [comment]
Thank you for your feedback. I will fix this ASAP.

**Comment by burhanyldz** [comment]
+1 Thanks for the theme. I have read your article and appreciate the effort. I will start my new ng2 project with this theme.

**Comment by mrholek** [comment]
I just fixed this problem, please check new version

**Comment by gvolkan** [comment]
hi, im getting error same kind. 


> CoreUI@1.0.0-alpha.2 start /Users/volkan/Development/Exercise/angular 2/CoreUI-Free-Bootstrap-Admin-Template/Angular2_Dev
> tsc && concurrently "tsc -w" "lite-server"

app/app.module.ts(8,10): error TS2305: Module '"/Users/volkan/Development/Exercise/angular 2/CoreUI-Free-Bootstrap-Admin-Template/Angular2_Dev/node_modules/ng2-charts/ng2-charts"' has no exported member 'CHART_DIRECTIVES'.

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.4.1
npm ERR! npm  v3.7.5
npm ERR! code ELIFECYCLE
npm ERR! CoreUI@1.0.0-alpha.2 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! Exit status 2

can you check that, too...

**Comment by burhanyldz** [comment]
same here.

**Comment by gvernile** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/Users/GianMarco/.npm-packages/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.10.7
3 info using node@v6.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle CoreUI@1.0.0-alpha.2~prestart: CoreUI@1.0.0-alpha.2
6 silly lifecycle CoreUI@1.0.0-alpha.2~prestart: no script for prestart, continuing
7 info lifecycle CoreUI@1.0.0-alpha.2~start: CoreUI@1.0.0-alpha.2
8 verbose lifecycle CoreUI@1.0.0-alpha.2~start: unsafe-perm in lifecycle true
9 verbose lifecycle CoreUI@1.0.0-alpha.2~start: PATH: /Users/GianMarco/.npm-packages/lib/node_modules/npm/bin/node-gyp-bin:/DevCode/Illuminati/admin/node_modules/.bin:/opt/local/bin:/opt/local/sbin:/Users/GianMarco/.npm-packages/bin:/DevCode/maven/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin:/bin:/DevCode/ant/bin:/usr/local/mongodb/bin:/usr/local/mysql-5.6.30-osx10.11-x86_64/bin:/Users/GianMarco/bin
10 verbose lifecycle CoreUI@1.0.0-alpha.2~start: CWD: /DevCode/Illuminati/admin
11 silly lifecycle CoreUI@1.0.0-alpha.2~start: Args: [ '-c', 'tsc && concurrently "tsc -w" "lite-server" ' ]
12 silly lifecycle CoreUI@1.0.0-alpha.2~start: Returned: code: 2  signal: null
13 info lifecycle CoreUI@1.0.0-alpha.2~start: Failed to exec start script
14 verbose stack Error: CoreUI@1.0.0-alpha.2 start: `tsc && concurrently "tsc -w" "lite-server" `
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/Users/GianMarco/.npm-packages/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/GianMarco/.npm-packages/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid CoreUI@1.0.0-alpha.2
16 verbose cwd /DevCode/Illuminati/admin
17 error Darwin 15.6.0
18 error argv "/usr/local/bin/node" "/Users/GianMarco/.npm-packages/bin/npm" "start"
19 error node v6.4.0
20 error npm  v3.10.7
21 error code ELIFECYCLE
22 error CoreUI@1.0.0-alpha.2 start: `tsc && concurrently "tsc -w" "lite-server" `
22 error Exit status 2
23 error Failed at the CoreUI@1.0.0-alpha.2 start script 'tsc && concurrently "tsc -w" "lite-server" '.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the CoreUI package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     tsc && concurrently "tsc -w" "lite-server"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs CoreUI
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls CoreUI
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by gvernile** [comment]
Hope fullstacktrace will help you to fix it. Thanks for your theme :)

**Comment by rbasniak** [comment]
I'm confirming the exact same error:

app/app.module.ts(8,10): error TS2305: Module '"C:/Users/rbasniak/Source/Repos/CoreUI-Free-Bootstrap-Admin-Template/Angular2_Dev/node_modules/ng2-charts/ng2-charts"' has no exported member 'CHART_DIRECTIVES'.

Just cloned the repository, ran NPM INSTALL and then NPM START and I get the error. I'm using node 6.4.0 and np, 3.10.3

**Comment by mrholek** [comment]
Thx, I'm working on it!

**Comment by mrholek** [comment]
I just fixed this issue, please download latest version.

**Comment by gvernile** [comment]
Sorry friend but still not working . I Attached my stacktrace

MacBook-Pro-di-Gian:Angular2_Dev GianMarco$ npm start

> CoreUI@1.0.0-alpha.2 start /DevCode/Illuminati/CoreUI-Free-Bootstrap-Admin-Template-master/Angular2_Dev
> tsc && concurrently "tsc -w" "lite-server"

node_modules/@types/jasmine/index.d.ts(73,9): error TS2375: Duplicate number index signature.
node_modules/@types/jasmine/index.d.ts(127,9): error TS2374: Duplicate string index signature.
node_modules/@types/node/index.d.ts(99,6): error TS2300: Duplicate identifier 'BufferEncoding'.
node_modules/@types/node/index.d.ts(544,26): error TS2300: Duplicate identifier 'Buffer'.
node_modules/@types/node/index.d.ts(544,50): error TS2300: Duplicate identifier 'SlowBuffer'.
node_modules/@types/node/index.d.ts(565,18): error TS2300: Duplicate identifier 'EventEmitter'.
node_modules/@types/node/index.d.ts(724,18): error TS2300: Duplicate identifier 'Agent'.
node_modules/@types/node/index.d.ts(769,18): error TS2300: Duplicate identifier 'Worker'.
node_modules/@types/node/index.d.ts(1070,18): error TS2300: Duplicate identifier 'Script'.
node_modules/@types/node/index.d.ts(1912,18): error TS2300: Duplicate identifier 'TLSSocket'.
node_modules/@types/node/index.d.ts(2203,18): error TS2300: Duplicate identifier 'Stream'.
node_modules/@types/node/index.d.ts(2214,18): error TS2300: Duplicate identifier 'Readable'.
node_modules/@types/node/index.d.ts(2237,18): error TS2300: Duplicate identifier 'Writable'.
node_modules/@types/node/index.d.ts(2255,18): error TS2300: Duplicate identifier 'Duplex'.
node_modules/@types/node/index.d.ts(2276,18): error TS2300: Duplicate identifier 'Transform'.
node_modules/@types/node/index.d.ts(2298,18): error TS2300: Duplicate identifier 'PassThrough'.
node_modules/@types/node/index.d.ts(2369,5): error TS2300: Duplicate identifier 'export='.
node_modules/@types/node/index.d.ts(2391,18): error TS2300: Duplicate identifier 'Domain'.
typings/globals/node/index.d.ts(78,6): error TS2300: Duplicate identifier 'BufferEncoding'.
typings/globals/node/index.d.ts(516,9): error TS2502: 'BuffType' is referenced directly or indirectly in its own type annotation.
typings/globals/node/index.d.ts(517,9): error TS2502: 'SlowBuffType' is referenced directly or indirectly in its own type annotation.
typings/globals/node/index.d.ts(518,26): error TS2300: Duplicate identifier 'Buffer'.
typings/globals/node/index.d.ts(518,50): error TS2300: Duplicate identifier 'SlowBuffer'.
typings/globals/node/index.d.ts(539,18): error TS2300: Duplicate identifier 'EventEmitter'.
typings/globals/node/index.d.ts(698,18): error TS2300: Duplicate identifier 'Agent'.
typings/globals/node/index.d.ts(743,18): error TS2300: Duplicate identifier 'Worker'.
typings/globals/node/index.d.ts(1044,18): error TS2300: Duplicate identifier 'Script'.
typings/globals/node/index.d.ts(1886,18): error TS2300: Duplicate identifier 'TLSSocket'.
typings/globals/node/index.d.ts(2177,18): error TS2300: Duplicate identifier 'Stream'.
typings/globals/node/index.d.ts(2188,18): error TS2300: Duplicate identifier 'Readable'.
typings/globals/node/index.d.ts(2211,18): error TS2300: Duplicate identifier 'Writable'.
typings/globals/node/index.d.ts(2229,18): error TS2300: Duplicate identifier 'Duplex'.
typings/globals/node/index.d.ts(2250,18): error TS2300: Duplicate identifier 'Transform'.
typings/globals/node/index.d.ts(2272,18): error TS2300: Duplicate identifier 'PassThrough'.
typings/globals/node/index.d.ts(2343,5): error TS2300: Duplicate identifier 'export='.
typings/globals/node/index.d.ts(2365,18): error TS2300: Duplicate identifier 'Domain'.

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/Users/GianMarco/.npm-packages/bin/npm" "start"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! CoreUI@1.0.0-alpha.2 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the CoreUI@1.0.0-alpha.2 start script 'tsc && concurrently "tsc -w" "lite-server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the CoreUI package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "tsc -w" "lite-server"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs CoreUI
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls CoreUI
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /DevCode/Illuminati/CoreUI-Free-Bootstrap-Admin-Template-master/Angular2_Dev/npm-debug.log

**Comment by mrholek** [comment]
I updated dependencies in package.json. Did you install them?

**Comment by gvernile** [comment]
yes of course, make npm install

**Comment by rbasniak** [comment]
Same here. Cloned a new copy, NPM INSTALL, then NPM START and I get exactly the same errors that gverniller.

**Comment by mrholek** [comment]
Do you have folder @types in node_modules?

**Comment by rbasniak** [comment]
Yes, there is a **@types** folder with 2 subfolders: **nodes** and **jasmine**.

**Comment by gvernile** [comment]
it is the same for me

**Comment by mrholek** [comment]
Can you paste your package.json file?

**Comment by gvernile** [comment]
{
  "name": "CoreUI",
  "version": "1.0.0-alpha.2",
  "description": "Open Source Bootstrap Admin Template",
  "author": "Łukasz Holeczek",
  "url": "http://coreui.io",
  "copyright": "Copyright 2016 creativeLabs Łukasz Holeczek",
  "license": "http://coreui.io/license",
  "scripts": {
      "start": "tsc && concurrently \"tsc -w\" \"lite-server\" ",
      "docker-build": "docker build -t ng2-quickstart .",
      "docker": "npm run docker-build && docker run -it --rm -p 3000:3000 -p 3001:3001 ng2-quickstart",
      "pree2e": "npm run webdriver:update",
      "e2e": "tsc && concurrently \"http-server -s\" \"protractor protractor.config.js\" --kill-others --success first",
      "lint": "tslint ./app/**/*.ts -t verbose",
      "lite": "lite-server",
      "postinstall": "typings install",
      "test": "tsc && concurrently \"tsc -w\" \"karma start karma.conf.js\"",
      "test-once": "tsc && karma start karma.conf.js --single-run",
      "tsc": "tsc",
      "tsc:w": "tsc -w",
      "typings": "typings",
      "webdriver:update": "webdriver-manager update"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.0.0-rc.6",
    "@angular/compiler": "2.0.0-rc.6",
    "@angular/compiler-cli": "0.6.0",
    "@angular/core": "2.0.0-rc.6",
    "@angular/forms": "2.0.0-rc.6",
    "@angular/http": "2.0.0-rc.6",
    "@angular/platform-browser": "2.0.0-rc.6",
    "@angular/platform-browser-dynamic": "2.0.0-rc.6",
    "@angular/router": "3.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.6",
    "angular2-in-memory-web-api": "0.0.18",
    "chart.js": "^2.2.1",
    "core-js": "^2.4.1",
    "ng2-bootstrap": "^1.1.2",
    "ng2-charts": "^1.2.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.11",
    "systemjs": "0.19.38",
    "zone.js": "^0.6.21",
    "moment": "^2.15.0"
  },
  "devDependencies": {
    "canonical-path": "0.0.2",
    "concurrently": "^2.2.0",
    "gulp": "^3.9.1",
    "gulp-concat": "^2.6.0",
    "gulp-sass": "^2.3.2",
    "http-server": "^0.9.0",
    "jasmine-core": "^2.5.1",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-htmlfile-reporter": "^0.3.4",
    "karma-jasmine": "^1.0.2",
    "lite-server": "^2.2.2",
    "lodash": "^4.11.1",
    "protractor": "^4.0.5",
    "rimraf": "^2.5.2",
    "tslint": "^3.15.1",
    "typescript": "^2.0.2",
    "typings": "^1.3.2"
  },
  "repository": {}
}

**Comment by mrholek** [comment]
I just uploaded new version can you check?

1. sudo npm install
2. sudo npm run typings install

**Comment by gvernile** [comment]
I have just try now. i have the same errors

**Comment by mrholek** [comment]
Ok, I know we is problem. I was using node 4.5.0 and npm 2.15.9. You are using latest version.

**Comment by gvernile** [comment]
and so? i need to downgrade the versions of the both?

**Comment by mrholek** [comment]
In npm 3+ node_modules/@types/jasmin is installed automaticly. No you don't need ti downgrade. I'll update package.json and it should works.

**Comment by gvernile** [comment]
ok . it sound great :)

**Comment by mrholek** [comment]
Please check new version?

**Comment by gvernile** [comment]
ok. now it works. thanks really a lot.

**Comment by AcademyLime** [comment]
thanks @mrholek and @gvernile.

**Comment by rbasniak** [comment]
Awesome, really thanks for the fast solution. Angular2 is working and I'll start looking into the code now... You're doing a really great job with this theme! =)
